version: "3.8"

services:
  api:
    build: .
    container_name: leaky-bucket-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network
    command: npm run dev
    volumes:
      - ./src:/app/src
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge